<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Cleaning data: ticket sales</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="mbta.html">MBTA</a>
</li>
<li>
  <a href="food.nb.html">World Food</a>
</li>
<li>
  <a href="school.html">School</a>
</li>
<li>
  <a href="ticket_sales.html">Ticket</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Cleaning data: ticket sales</h1>

</div>


<p>Your first dataset describes online ticket sales for various events across the country. It’s stored as a Comma-Separated Value (CSV) file called sales.csv</p>
<pre class="r"><code># Import sales.csv: sales
sales &lt;- read.csv(&quot;sales.csv&quot;, stringsAsFactors = FALSE)</code></pre>
<p>The first step when preparing to clean data is to inspect it.</p>
<pre class="r"><code># View dimensions of sales
dim(sales)</code></pre>
<pre><code>## [1] 5000   46</code></pre>
<pre class="r"><code># Inspect first 6 rows of sales
head(sales)</code></pre>
<pre><code>##   X             event_id       primary_act_id     secondary_act_id  purch_party_lkup_id
## 1 1 abcaf1adb99a935fc661 43f0436b905bfa7c2eec b85143bf51323b72e53c 7dfa56dd7d5956b17587
## 2 2 6c56d7f08c95f2aa453c 1a3e9aecd0617706a794 f53529c5679ea6ca5a48 4f9e6fc637eaf7b736c2
## 3 3 c7ab4524a121f9d687d2 4b677c3f5bec71eec8d1 b85143bf51323b72e53c 6c2545703bd527a7144d
## 4 4 394cb493f893be9b9ed1 b1ccea01ad6ef8522796 b85143bf51323b72e53c 527d6b1eaffc69ddd882
## 5 5 55b5f67e618557929f48 91c03a34b562436efa3c b85143bf51323b72e53c 8bd62c394a35213bdf52
## 6 6 4f10fd8b9f550352bd56 ac4b847b3fde66f2117e 63814f3d63317f1b56c4 3b3a628f83135acd0676
##                                                       event_name
## 1 Xfinity Center Mansfield Premier Parking: Florida Georgia Line
## 2                  Gorge Camping - dave matthews band - sept 3-7
## 3                    Dodge Theatre Adams Street Parking - benise
## 4   Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow
## 5                                  Premier Parking - motley crue
## 6                                      Fast Lane Access: Journey
##                           primary_act_name secondary_act_name major_cat_name         minor_cat_name
## 1 XFINITY Center Mansfield Premier Parking               NULL           MISC                PARKING
## 2                            Gorge Camping Dave Matthews Band           MISC                CAMPING
## 3                            Parking Event               NULL           MISC                PARKING
## 4         Gexa Energy Pavilion VIP Parking               NULL           MISC                PARKING
## 5 White River Amphitheatre Premier Parking               NULL           MISC                PARKING
## 6                         Fast Lane Access            Journey           MISC SPECIAL ENTRY (UPSELL)
##   la_event_type_cat                                                event_disp_name
## 1           PARKING Xfinity Center Mansfield Premier Parking: Florida Georgia Line
## 2           INVALID                  Gorge Camping - dave matthews band - sept 3-7
## 3           PARKING                    Dodge Theatre Adams Street Parking - benise
## 4           PARKING   Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow
## 5           PARKING                                  Premier Parking - motley crue
## 6            UPSELL                                      Fast Lane Access: Journey
##                                                                                                                                                    ticket_text
## 1    THIS TICKET IS VALID        FOR PARKING ONLY         GOOD THIS DAY ONLY       PREMIER PARKING PASS    XFINITY CENTER,LOTS 4 PM  SAT SEP 12 2015 7:30 PM  
## 2                                                                %OVERNIGHT C A M P I N G%* * * * * *%GORGE CAMPGROUND%* GOOD THIS DATE ONLY *%SEP 3 - 6, 2009
## 3                               ADAMS STREET GARAGE%PARKING FOR 4/21/06 ONLY%DODGE THEATRE PARKING PASS%ENTRANCE ON ADAMS STREET%BENISE%GARAGE OPENS AT 6:00PM
## 4    THIS TICKET IS VALID        FOR PARKING ONLY      GOOD FOR THIS DATE ONLY       VIP PARKING PASS        GEXA ENERGY PAVILION    FRI SEP 02 2011 7:00 PM  
## 5                              THIS TICKET IS VALID%FOR PARKING ONLY%GOOD THIS DATE ONLY%PREMIER PARKING PASS%WHITE RIVER AMPHITHEATRE%SAT JUL 30, 2005 6:00PM
## 6         FAST LANE                  JOURNEY               FAST LANE EVENT         THIS IS NOT A TICKET    SAN MANUEL AMPHITHEATER   SAT JUL 21 2012 7:00 PM  
##   tickets_purchased_qty trans_face_val_amt delivery_type_cd     event_date_time   event_dt presale_dt
## 1                     1                 45          eTicket 2015-09-12 23:30:00 2015-09-12       NULL
## 2                     1                 75       TicketFast 2009-09-05 01:00:00 2009-09-04       NULL
## 3                     1                  5       TicketFast 2006-04-22 01:30:00 2006-04-21       NULL
## 4                     1                 20             Mail 2011-09-03 00:00:00 2011-09-02       NULL
## 5                     1                 20             Mail 2005-07-31 01:00:00 2005-07-30 2005-03-02
## 6                     2                 10       TicketFast 2012-07-22 02:00:00 2012-07-21       NULL
##    onsale_dt sales_ord_create_dttm sales_ord_tran_dt   print_dt timezn_nm     venue_city   venue_state
## 1 2015-05-15   2015-09-11 18:17:45        2015-09-11 2015-09-12       EST      MANSFIELD MASSACHUSETTS
## 2 2009-03-13   2009-07-06 00:00:00        2009-07-05 2009-09-01       PST         QUINCY    WASHINGTON
## 3 2006-02-25   2006-04-05 00:00:00        2006-04-05 2006-04-05       MST        PHOENIX       ARIZONA
## 4 2011-04-22   2011-07-01 17:38:50        2011-07-01 2011-07-06       CST         DALLAS         TEXAS
## 5 2005-03-04   2005-06-18 00:00:00        2005-06-18 2005-06-28       PST         AUBURN    WASHINGTON
## 6 2012-04-11   2012-07-21 17:20:18        2012-07-21 2012-07-21       PST SAN BERNARDINO    CALIFORNIA
##   venue_postal_cd_sgmt_1           sales_platform_cd print_flg la_valid_tkt_event_flg  fin_mkt_nm
## 1                  02048 www.concerts.livenation.com        T                      N       Boston
## 2                  98848                        NULL        T                      N      Seattle
## 3                  85003                        NULL        T                      N      Arizona
## 4                  75210                        NULL        T                      N       Dallas
## 5                  98092                        NULL        T                      N      Seattle
## 6                  92407          www.livenation.com        T                      N  Los Angeles
##   web_session_cookie_val gndr_cd age_yr income_amt edu_val edu_1st_indv_val edu_2nd_indv_val
## 1   7dfa56dd7d5956b17587    &lt;NA&gt;   &lt;NA&gt;       &lt;NA&gt;    &lt;NA&gt;             &lt;NA&gt;             &lt;NA&gt;
## 2   4f9e6fc637eaf7b736c2    &lt;NA&gt;   &lt;NA&gt;       &lt;NA&gt;    &lt;NA&gt;             &lt;NA&gt;             &lt;NA&gt;
## 3   6c2545703bd527a7144d    &lt;NA&gt;   &lt;NA&gt;       &lt;NA&gt;    &lt;NA&gt;             &lt;NA&gt;             &lt;NA&gt;
## 4   527d6b1eaffc69ddd882    &lt;NA&gt;   &lt;NA&gt;       &lt;NA&gt;    &lt;NA&gt;             &lt;NA&gt;             &lt;NA&gt;
## 5   8bd62c394a35213bdf52    &lt;NA&gt;   &lt;NA&gt;       &lt;NA&gt;    &lt;NA&gt;             &lt;NA&gt;             &lt;NA&gt;
## 6   3b3a628f83135acd0676    &lt;NA&gt;   &lt;NA&gt;       &lt;NA&gt;    &lt;NA&gt;             &lt;NA&gt;             &lt;NA&gt;
##   adults_in_hh_num married_ind child_present_ind home_owner_ind occpn_val occpn_1st_val occpn_2nd_val
## 1             &lt;NA&gt;        &lt;NA&gt;              &lt;NA&gt;           &lt;NA&gt;      &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 2             &lt;NA&gt;        &lt;NA&gt;              &lt;NA&gt;           &lt;NA&gt;      &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 3             &lt;NA&gt;        &lt;NA&gt;              &lt;NA&gt;           &lt;NA&gt;      &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 4             &lt;NA&gt;        &lt;NA&gt;              &lt;NA&gt;           &lt;NA&gt;      &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 5             &lt;NA&gt;        &lt;NA&gt;              &lt;NA&gt;           &lt;NA&gt;      &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
## 6             &lt;NA&gt;        &lt;NA&gt;              &lt;NA&gt;           &lt;NA&gt;      &lt;NA&gt;          &lt;NA&gt;          &lt;NA&gt;
##   dist_to_ven
## 1          NA
## 2          59
## 3          NA
## 4          NA
## 5          NA
## 6          NA</code></pre>
<pre class="r"><code># View column names of sales
names(sales)</code></pre>
<pre><code>##  [1] &quot;X&quot;                      &quot;event_id&quot;               &quot;primary_act_id&quot;        
##  [4] &quot;secondary_act_id&quot;       &quot;purch_party_lkup_id&quot;    &quot;event_name&quot;            
##  [7] &quot;primary_act_name&quot;       &quot;secondary_act_name&quot;     &quot;major_cat_name&quot;        
## [10] &quot;minor_cat_name&quot;         &quot;la_event_type_cat&quot;      &quot;event_disp_name&quot;       
## [13] &quot;ticket_text&quot;            &quot;tickets_purchased_qty&quot;  &quot;trans_face_val_amt&quot;    
## [16] &quot;delivery_type_cd&quot;       &quot;event_date_time&quot;        &quot;event_dt&quot;              
## [19] &quot;presale_dt&quot;             &quot;onsale_dt&quot;              &quot;sales_ord_create_dttm&quot; 
## [22] &quot;sales_ord_tran_dt&quot;      &quot;print_dt&quot;               &quot;timezn_nm&quot;             
## [25] &quot;venue_city&quot;             &quot;venue_state&quot;            &quot;venue_postal_cd_sgmt_1&quot;
## [28] &quot;sales_platform_cd&quot;      &quot;print_flg&quot;              &quot;la_valid_tkt_event_flg&quot;
## [31] &quot;fin_mkt_nm&quot;             &quot;web_session_cookie_val&quot; &quot;gndr_cd&quot;               
## [34] &quot;age_yr&quot;                 &quot;income_amt&quot;             &quot;edu_val&quot;               
## [37] &quot;edu_1st_indv_val&quot;       &quot;edu_2nd_indv_val&quot;       &quot;adults_in_hh_num&quot;      
## [40] &quot;married_ind&quot;            &quot;child_present_ind&quot;      &quot;home_owner_ind&quot;        
## [43] &quot;occpn_val&quot;              &quot;occpn_1st_val&quot;          &quot;occpn_2nd_val&quot;         
## [46] &quot;dist_to_ven&quot;</code></pre>
<p>Notice how the rows appear to represent individual purchases and the columns contain different pieces of information about each purchase.</p>
<p>Let´s summarise the data.</p>
<pre class="r"><code># Look at structure of sales
str(sales)</code></pre>
<pre><code>## &#39;data.frame&#39;:    5000 obs. of  46 variables:
##  $ X                     : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ event_id              : chr  &quot;abcaf1adb99a935fc661&quot; &quot;6c56d7f08c95f2aa453c&quot; &quot;c7ab4524a121f9d687d2&quot; &quot;394cb493f893be9b9ed1&quot; ...
##  $ primary_act_id        : chr  &quot;43f0436b905bfa7c2eec&quot; &quot;1a3e9aecd0617706a794&quot; &quot;4b677c3f5bec71eec8d1&quot; &quot;b1ccea01ad6ef8522796&quot; ...
##  $ secondary_act_id      : chr  &quot;b85143bf51323b72e53c&quot; &quot;f53529c5679ea6ca5a48&quot; &quot;b85143bf51323b72e53c&quot; &quot;b85143bf51323b72e53c&quot; ...
##  $ purch_party_lkup_id   : chr  &quot;7dfa56dd7d5956b17587&quot; &quot;4f9e6fc637eaf7b736c2&quot; &quot;6c2545703bd527a7144d&quot; &quot;527d6b1eaffc69ddd882&quot; ...
##  $ event_name            : chr  &quot;Xfinity Center Mansfield Premier Parking: Florida Georgia Line&quot; &quot;Gorge Camping - dave matthews band - sept 3-7&quot; &quot;Dodge Theatre Adams Street Parking - benise&quot; &quot;Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow&quot; ...
##  $ primary_act_name      : chr  &quot;XFINITY Center Mansfield Premier Parking&quot; &quot;Gorge Camping&quot; &quot;Parking Event&quot; &quot;Gexa Energy Pavilion VIP Parking&quot; ...
##  $ secondary_act_name    : chr  &quot;NULL&quot; &quot;Dave Matthews Band&quot; &quot;NULL&quot; &quot;NULL&quot; ...
##  $ major_cat_name        : chr  &quot;MISC&quot; &quot;MISC&quot; &quot;MISC&quot; &quot;MISC&quot; ...
##  $ minor_cat_name        : chr  &quot;PARKING&quot; &quot;CAMPING&quot; &quot;PARKING&quot; &quot;PARKING&quot; ...
##  $ la_event_type_cat     : chr  &quot;PARKING&quot; &quot;INVALID&quot; &quot;PARKING&quot; &quot;PARKING&quot; ...
##  $ event_disp_name       : chr  &quot;Xfinity Center Mansfield Premier Parking: Florida Georgia Line&quot; &quot;Gorge Camping - dave matthews band - sept 3-7&quot; &quot;Dodge Theatre Adams Street Parking - benise&quot; &quot;Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow&quot; ...
##  $ ticket_text           : chr  &quot;   THIS TICKET IS VALID        FOR PARKING ONLY         GOOD THIS DAY ONLY       PREMIER PARKING PASS    XFINIT&quot;| __truncated__ &quot;%OVERNIGHT C A M P I N G%* * * * * *%GORGE CAMPGROUND%* GOOD THIS DATE ONLY *%SEP 3 - 6, 2009&quot; &quot;ADAMS STREET GARAGE%PARKING FOR 4/21/06 ONLY%DODGE THEATRE PARKING PASS%ENTRANCE ON ADAMS STREET%BENISE%GARAGE OPENS AT 6:00PM&quot; &quot;   THIS TICKET IS VALID        FOR PARKING ONLY      GOOD FOR THIS DATE ONLY       VIP PARKING PASS        GEXA&quot;| __truncated__ ...
##  $ tickets_purchased_qty : int  1 1 1 1 1 2 1 1 1 1 ...
##  $ trans_face_val_amt    : num  45 75 5 20 20 10 30 28 20 25 ...
##  $ delivery_type_cd      : chr  &quot;eTicket&quot; &quot;TicketFast&quot; &quot;TicketFast&quot; &quot;Mail&quot; ...
##  $ event_date_time       : chr  &quot;2015-09-12 23:30:00&quot; &quot;2009-09-05 01:00:00&quot; &quot;2006-04-22 01:30:00&quot; &quot;2011-09-03 00:00:00&quot; ...
##  $ event_dt              : chr  &quot;2015-09-12&quot; &quot;2009-09-04&quot; &quot;2006-04-21&quot; &quot;2011-09-02&quot; ...
##  $ presale_dt            : chr  &quot;NULL&quot; &quot;NULL&quot; &quot;NULL&quot; &quot;NULL&quot; ...
##  $ onsale_dt             : chr  &quot;2015-05-15&quot; &quot;2009-03-13&quot; &quot;2006-02-25&quot; &quot;2011-04-22&quot; ...
##  $ sales_ord_create_dttm : chr  &quot;2015-09-11 18:17:45&quot; &quot;2009-07-06 00:00:00&quot; &quot;2006-04-05 00:00:00&quot; &quot;2011-07-01 17:38:50&quot; ...
##  $ sales_ord_tran_dt     : chr  &quot;2015-09-11&quot; &quot;2009-07-05&quot; &quot;2006-04-05&quot; &quot;2011-07-01&quot; ...
##  $ print_dt              : chr  &quot;2015-09-12&quot; &quot;2009-09-01&quot; &quot;2006-04-05&quot; &quot;2011-07-06&quot; ...
##  $ timezn_nm             : chr  &quot;EST&quot; &quot;PST&quot; &quot;MST&quot; &quot;CST&quot; ...
##  $ venue_city            : chr  &quot;MANSFIELD&quot; &quot;QUINCY&quot; &quot;PHOENIX&quot; &quot;DALLAS&quot; ...
##  $ venue_state           : chr  &quot;MASSACHUSETTS&quot; &quot;WASHINGTON&quot; &quot;ARIZONA&quot; &quot;TEXAS&quot; ...
##  $ venue_postal_cd_sgmt_1: chr  &quot;02048&quot; &quot;98848&quot; &quot;85003&quot; &quot;75210&quot; ...
##  $ sales_platform_cd     : chr  &quot;www.concerts.livenation.com&quot; &quot;NULL&quot; &quot;NULL&quot; &quot;NULL&quot; ...
##  $ print_flg             : chr  &quot;T &quot; &quot;T &quot; &quot;T &quot; &quot;T &quot; ...
##  $ la_valid_tkt_event_flg: chr  &quot;N &quot; &quot;N &quot; &quot;N &quot; &quot;N &quot; ...
##  $ fin_mkt_nm            : chr  &quot;Boston&quot; &quot;Seattle&quot; &quot;Arizona&quot; &quot;Dallas&quot; ...
##  $ web_session_cookie_val: chr  &quot;7dfa56dd7d5956b17587&quot; &quot;4f9e6fc637eaf7b736c2&quot; &quot;6c2545703bd527a7144d&quot; &quot;527d6b1eaffc69ddd882&quot; ...
##  $ gndr_cd               : chr  NA NA NA NA ...
##  $ age_yr                : chr  NA NA NA NA ...
##  $ income_amt            : chr  NA NA NA NA ...
##  $ edu_val               : chr  NA NA NA NA ...
##  $ edu_1st_indv_val      : chr  NA NA NA NA ...
##  $ edu_2nd_indv_val      : chr  NA NA NA NA ...
##  $ adults_in_hh_num      : chr  NA NA NA NA ...
##  $ married_ind           : chr  NA NA NA NA ...
##  $ child_present_ind     : chr  NA NA NA NA ...
##  $ home_owner_ind        : chr  NA NA NA NA ...
##  $ occpn_val             : chr  NA NA NA NA ...
##  $ occpn_1st_val         : chr  NA NA NA NA ...
##  $ occpn_2nd_val         : chr  NA NA NA NA ...
##  $ dist_to_ven           : int  NA 59 NA NA NA NA NA NA NA NA ...</code></pre>
<pre class="r"><code># View a summary of sales
summary(sales)</code></pre>
<pre><code>##        X          event_id         primary_act_id     secondary_act_id   purch_party_lkup_id
##  Min.   :   1   Length:5000        Length:5000        Length:5000        Length:5000        
##  1st Qu.:1251   Class :character   Class :character   Class :character   Class :character   
##  Median :2500   Mode  :character   Mode  :character   Mode  :character   Mode  :character   
##  Mean   :2500                                                                               
##  3rd Qu.:3750                                                                               
##  Max.   :5000                                                                               
##                                                                                             
##   event_name        primary_act_name   secondary_act_name major_cat_name     minor_cat_name    
##  Length:5000        Length:5000        Length:5000        Length:5000        Length:5000       
##  Class :character   Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                                                
##                                                                                                
##                                                                                                
##                                                                                                
##  la_event_type_cat  event_disp_name    ticket_text        tickets_purchased_qty trans_face_val_amt
##  Length:5000        Length:5000        Length:5000        Min.   :1.000         Min.   :   1.00   
##  Class :character   Class :character   Class :character   1st Qu.:1.000         1st Qu.:  20.00   
##  Mode  :character   Mode  :character   Mode  :character   Median :1.000         Median :  30.00   
##                                                           Mean   :1.639         Mean   :  77.08   
##                                                           3rd Qu.:2.000         3rd Qu.:  85.00   
##                                                           Max.   :8.000         Max.   :1520.88   
##                                                                                                   
##  delivery_type_cd   event_date_time      event_dt          presale_dt         onsale_dt        
##  Length:5000        Length:5000        Length:5000        Length:5000        Length:5000       
##  Class :character   Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                                                
##                                                                                                
##                                                                                                
##                                                                                                
##  sales_ord_create_dttm sales_ord_tran_dt    print_dt          timezn_nm          venue_city       
##  Length:5000           Length:5000        Length:5000        Length:5000        Length:5000       
##  Class :character      Class :character   Class :character   Class :character   Class :character  
##  Mode  :character      Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                                                   
##                                                                                                   
##                                                                                                   
##                                                                                                   
##  venue_state        venue_postal_cd_sgmt_1 sales_platform_cd   print_flg        
##  Length:5000        Length:5000            Length:5000        Length:5000       
##  Class :character   Class :character       Class :character   Class :character  
##  Mode  :character   Mode  :character       Mode  :character   Mode  :character  
##                                                                                 
##                                                                                 
##                                                                                 
##                                                                                 
##  la_valid_tkt_event_flg  fin_mkt_nm        web_session_cookie_val   gndr_cd         
##  Length:5000            Length:5000        Length:5000            Length:5000       
##  Class :character       Class :character   Class :character       Class :character  
##  Mode  :character       Mode  :character   Mode  :character       Mode  :character  
##                                                                                     
##                                                                                     
##                                                                                     
##                                                                                     
##     age_yr           income_amt          edu_val          edu_1st_indv_val   edu_2nd_indv_val  
##  Length:5000        Length:5000        Length:5000        Length:5000        Length:5000       
##  Class :character   Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                                                
##                                                                                                
##                                                                                                
##                                                                                                
##  adults_in_hh_num   married_ind        child_present_ind  home_owner_ind      occpn_val        
##  Length:5000        Length:5000        Length:5000        Length:5000        Length:5000       
##  Class :character   Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                                                
##                                                                                                
##                                                                                                
##                                                                                                
##  occpn_1st_val      occpn_2nd_val       dist_to_ven    
##  Length:5000        Length:5000        Min.   :   0.0  
##  Class :character   Class :character   1st Qu.:  12.0  
##  Mode  :character   Mode  :character   Median :  26.0  
##                                        Mean   : 158.2  
##                                        3rd Qu.:  77.5  
##                                        Max.   :2548.0  
##                                        NA&#39;s   :4677</code></pre>
<pre class="r"><code># Load dplyr
library(dplyr)

# Get a glimpse of sales
glimpse(sales)</code></pre>
<pre><code>## Observations: 5,000
## Variables: 46
## $ X                      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, ...
## $ event_id               &lt;chr&gt; &quot;abcaf1adb99a935fc661&quot;, &quot;6c56d7f08c95f2aa453c&quot;, &quot;c7ab4524a121f9d687...
## $ primary_act_id         &lt;chr&gt; &quot;43f0436b905bfa7c2eec&quot;, &quot;1a3e9aecd0617706a794&quot;, &quot;4b677c3f5bec71eec8...
## $ secondary_act_id       &lt;chr&gt; &quot;b85143bf51323b72e53c&quot;, &quot;f53529c5679ea6ca5a48&quot;, &quot;b85143bf51323b72e5...
## $ purch_party_lkup_id    &lt;chr&gt; &quot;7dfa56dd7d5956b17587&quot;, &quot;4f9e6fc637eaf7b736c2&quot;, &quot;6c2545703bd527a714...
## $ event_name             &lt;chr&gt; &quot;Xfinity Center Mansfield Premier Parking: Florida Georgia Line&quot;, &quot;...
## $ primary_act_name       &lt;chr&gt; &quot;XFINITY Center Mansfield Premier Parking&quot;, &quot;Gorge Camping&quot;, &quot;Parki...
## $ secondary_act_name     &lt;chr&gt; &quot;NULL&quot;, &quot;Dave Matthews Band&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;Journey&quot;, &quot;N...
## $ major_cat_name         &lt;chr&gt; &quot;MISC&quot;, &quot;MISC&quot;, &quot;MISC&quot;, &quot;MISC&quot;, &quot;MISC&quot;, &quot;MISC&quot;, &quot;MISC&quot;, &quot;MISC&quot;, &quot;MI...
## $ minor_cat_name         &lt;chr&gt; &quot;PARKING&quot;, &quot;CAMPING&quot;, &quot;PARKING&quot;, &quot;PARKING&quot;, &quot;PARKING&quot;, &quot;SPECIAL ENT...
## $ la_event_type_cat      &lt;chr&gt; &quot;PARKING&quot;, &quot;INVALID&quot;, &quot;PARKING&quot;, &quot;PARKING&quot;, &quot;PARKING&quot;, &quot;UPSELL&quot;, &quot;P...
## $ event_disp_name        &lt;chr&gt; &quot;Xfinity Center Mansfield Premier Parking: Florida Georgia Line&quot;, &quot;...
## $ ticket_text            &lt;chr&gt; &quot;   THIS TICKET IS VALID        FOR PARKING ONLY         GOOD THIS ...
## $ tickets_purchased_qty  &lt;int&gt; 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 4, 1, 1, 1, 2, 1, 1, 1, 1, 4, 2...
## $ trans_face_val_amt     &lt;dbl&gt; 45.0, 75.0, 5.0, 20.0, 20.0, 10.0, 30.0, 28.0, 20.0, 25.0, 20.0, 90...
## $ delivery_type_cd       &lt;chr&gt; &quot;eTicket&quot;, &quot;TicketFast&quot;, &quot;TicketFast&quot;, &quot;Mail&quot;, &quot;Mail&quot;, &quot;TicketFast&quot;...
## $ event_date_time        &lt;chr&gt; &quot;2015-09-12 23:30:00&quot;, &quot;2009-09-05 01:00:00&quot;, &quot;2006-04-22 01:30:00&quot;...
## $ event_dt               &lt;chr&gt; &quot;2015-09-12&quot;, &quot;2009-09-04&quot;, &quot;2006-04-21&quot;, &quot;2011-09-02&quot;, &quot;2005-07-30...
## $ presale_dt             &lt;chr&gt; &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;2005-03-02&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL...
## $ onsale_dt              &lt;chr&gt; &quot;2015-05-15&quot;, &quot;2009-03-13&quot;, &quot;2006-02-25&quot;, &quot;2011-04-22&quot;, &quot;2005-03-04...
## $ sales_ord_create_dttm  &lt;chr&gt; &quot;2015-09-11 18:17:45&quot;, &quot;2009-07-06 00:00:00&quot;, &quot;2006-04-05 00:00:00&quot;...
## $ sales_ord_tran_dt      &lt;chr&gt; &quot;2015-09-11&quot;, &quot;2009-07-05&quot;, &quot;2006-04-05&quot;, &quot;2011-07-01&quot;, &quot;2005-06-18...
## $ print_dt               &lt;chr&gt; &quot;2015-09-12&quot;, &quot;2009-09-01&quot;, &quot;2006-04-05&quot;, &quot;2011-07-06&quot;, &quot;2005-06-28...
## $ timezn_nm              &lt;chr&gt; &quot;EST&quot;, &quot;PST&quot;, &quot;MST&quot;, &quot;CST&quot;, &quot;PST&quot;, &quot;PST&quot;, &quot;EST&quot;, &quot;PST&quot;, &quot;MST&quot;, &quot;PST...
## $ venue_city             &lt;chr&gt; &quot;MANSFIELD&quot;, &quot;QUINCY&quot;, &quot;PHOENIX&quot;, &quot;DALLAS&quot;, &quot;AUBURN&quot;, &quot;SAN BERNARDI...
## $ venue_state            &lt;chr&gt; &quot;MASSACHUSETTS&quot;, &quot;WASHINGTON&quot;, &quot;ARIZONA&quot;, &quot;TEXAS&quot;, &quot;WASHINGTON&quot;, &quot;C...
## $ venue_postal_cd_sgmt_1 &lt;chr&gt; &quot;02048&quot;, &quot;98848&quot;, &quot;85003&quot;, &quot;75210&quot;, &quot;98092&quot;, &quot;92407&quot;, &quot;07733&quot;, &quot;980...
## $ sales_platform_cd      &lt;chr&gt; &quot;www.concerts.livenation.com&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;www...
## $ print_flg              &lt;chr&gt; &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;T &quot;, &quot;...
## $ la_valid_tkt_event_flg &lt;chr&gt; &quot;N &quot;, &quot;N &quot;, &quot;N &quot;, &quot;N &quot;, &quot;N &quot;, &quot;N &quot;, &quot;N &quot;, &quot;N &quot;, &quot;N &quot;, &quot;Y &quot;, &quot;N &quot;, &quot;...
## $ fin_mkt_nm             &lt;chr&gt; &quot;Boston&quot;, &quot;Seattle&quot;, &quot;Arizona&quot;, &quot;Dallas&quot;, &quot;Seattle&quot;, &quot;Los Angeles&quot;,...
## $ web_session_cookie_val &lt;chr&gt; &quot;7dfa56dd7d5956b17587&quot;, &quot;4f9e6fc637eaf7b736c2&quot;, &quot;6c2545703bd527a714...
## $ gndr_cd                &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;M&quot;, NA, NA, NA, &quot;M&quot;, NA, NA, &quot;NULL&quot;, NA, N...
## $ age_yr                 &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;28&quot;, NA, NA, NA, &quot;80&quot;, NA, NA, &quot;NULL&quot;, NA,...
## $ income_amt             &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;112500&quot;, NA, NA, NA, &quot;200000&quot;, NA, NA, &quot;NU...
## $ edu_val                &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;High School&quot;, NA, NA, NA, &quot;High School&quot;, N...
## $ edu_1st_indv_val       &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;High School&quot;, NA, NA, NA, &quot;High School&quot;, N...
## $ edu_2nd_indv_val       &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;NULL&quot;, NA, NA, NA, &quot;High School&quot;, NA, NA, ...
## $ adults_in_hh_num       &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;4&quot;, NA, NA, NA, &quot;2&quot;, NA, NA, &quot;NULL&quot;, NA, N...
## $ married_ind            &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;0&quot;, NA, NA, NA, &quot;1&quot;, NA, NA, &quot;NULL&quot;, NA, N...
## $ child_present_ind      &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;1&quot;, NA, NA, NA, &quot;NULL&quot;, NA, NA, &quot;NULL&quot;, NA...
## $ home_owner_ind         &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;0&quot;, NA, NA, NA, &quot;1&quot;, NA, NA, &quot;NULL&quot;, NA, N...
## $ occpn_val              &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;NULL&quot;, NA, NA, NA, &quot;Retired&quot;, NA, NA, &quot;NUL...
## $ occpn_1st_val          &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;Craftsman Blue Collar&quot;, NA, NA, NA, &quot;Retir...
## $ occpn_2nd_val          &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;NULL&quot;, NA, NA, NA, &quot;Retired&quot;, NA, NA, &quot;NUL...
## $ dist_to_ven            &lt;int&gt; NA, 59, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 36, NA,...</code></pre>
<p>You may have noticed that the first column of data is just a duplication of the row numbers. Not very useful. We can delete that column.</p>
<pre class="r"><code># Remove the first column of sales: sales2
sales2 &lt;- sales[-1]</code></pre>
<p>Many of the columns have information that’s of no use to us. For example, the first four columns contain internal codes representing particular events. The last fifteen columns also aren’t worth keeping; there are too many missing values to make them worthwhile.</p>
<p>An easy way to get rid of unnecessary columns is to create a vector containing the column indices you want to keep, then subset the data based on that vector using single bracket subsetting.</p>
<pre class="r"><code># Define a vector of column indices: keep
keep &lt;- c(5:(ncol(sales2)-15))

# Subset sales2 using keep: sales3
sales3 &lt;- sales2[keep]</code></pre>
<p>Some of the columns in your data frame include multiple pieces of information that should be in separate columns. In this exercise, you will separate such a column into two: one for date and one for time.</p>
<pre class="r"><code># Load tidyr
library(tidyr)

# Split event_date_time: sales4
sales4 &lt;- separate(sales3, event_date_time,
                   c(&quot;event_dt&quot;, &quot;event_time&quot;), sep = &quot; &quot;)

# Split sales_ord_create_dttm: sales5
sales5 &lt;- separate(sales4, sales_ord_create_dttm,
                   c(&quot;ord_create_dt&quot;, &quot;ord_create_time&quot;), sep = &quot; &quot;)</code></pre>
<pre><code>## Warning: Expected 2 pieces. Missing pieces filled with `NA` in 4 rows [2516, 3863, 4082, 4183].</code></pre>
<p>Looks like that second call to separate() threw a warning. Not to worry; warnings aren’t as bad as error messages. It’s not saying that the command didn’t execute; it’s just a heads-up that something unusual happened.</p>
<p>The warning says Too few values at 4 locations. You may be able to guess already what the issue is, but it’s still good to take a look.</p>
<p>The locations (i.e. rows) given in the warning are 2516, 3863, 4082, and 4183. Have a look at the contents of the sales_ord_create_dttm column in those rows.</p>
<pre class="r"><code># Define an issues vector
issues &lt;- c(2516, 3863, 4082, 4183)

# Print values of sales_ord_create_dttm at these indices
print(sales3$sales_ord_create_dttm[issues])</code></pre>
<pre><code>## [1] &quot;NULL&quot; &quot;NULL&quot; &quot;NULL&quot; &quot;NULL&quot;</code></pre>
<pre class="r"><code># Print a well-behaved value of sales_ord_create_dttm
print(sales3$sales_ord_create_dttm[2517])</code></pre>
<pre><code>## [1] &quot;2013-08-04 23:07:19&quot;</code></pre>
<p>The warning was just because of four missing values. You’ll ignore them for now, but if your analysis depended on complete date/time information, you would probably need to delete those rows.</p>
<p>Some of the columns in your dataset contain dates of different events. Right now, they are stored as character strings. That’s fine if all you want to do is look up the date associated with an event, but if you want to do any comparisons or math with the dates, it’s MUCH easier to store them as Date objects.</p>
<p>Luckily, all of the date columns in this dataset have the substring “dt” in their name, so you can use the str_detect() function of the stringr package to find the date columns. Then you can coerce them to Date objects using a function from the lubridate package.</p>
<p>You’ll use lapply() to apply the appropriate lubridate function to all of the columns that contain dates. Recall the following syntax for lapply() applied to some data frame columns of interest:</p>
<pre><code>lapply(my_data_frame[, cols], function_name)</code></pre>
<p>Also recall that function names in lubridate combine the letters y, m, d, h, m, and s depending on the format of the date/time string being read in.</p>
<pre class="r"><code># Load stringr
library(stringr)

# Find columns of sales5 containing &quot;dt&quot;: date_cols
date_cols &lt;- str_detect(names(sales5), &quot;dt&quot;)

# Load lubridate
library(lubridate)</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:data.table&#39;:
## 
##     hour, isoweek, mday, minute, month, quarter, second, wday, week, yday, year</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date</code></pre>
<pre class="r"><code># Coerce date columns into Date objects
sales5[, date_cols] &lt;- lapply(sales5[, date_cols], ymd)</code></pre>
<pre><code>## Warning: 2892 failed to parse.</code></pre>
<pre><code>## Warning: 101 failed to parse.</code></pre>
<pre><code>## Warning: 4 failed to parse.</code></pre>
<pre><code>## Warning: 424 failed to parse.</code></pre>
<p>There were a few more warnings…</p>
<p>Some of the calls to ymd() caused a failure to parse warning. That’s probably because of more missing data, but again, it’s good to check to be sure.</p>
<p>See if the number of missing values in each column is the same as the number of rows that failed to parse in the previously.</p>
<pre class="r"><code># Find date columns (don&#39;t change)
date_cols &lt;- str_detect(names(sales5), &quot;dt&quot;)

# Create logical vectors indicating missing values (don&#39;t change)
missing &lt;- lapply(sales5[, date_cols], is.na)

# Create a numerical vector that counts missing values: num_missing
num_missing &lt;- sapply(missing, sum)

# Print num_missing
print(num_missing)</code></pre>
<pre><code>##          event_dt        presale_dt         onsale_dt     ord_create_dt sales_ord_tran_dt 
##                 0              2892               101                 4                 0 
##          print_dt 
##               424</code></pre>
<p>It was missing data again.</p>
<p>Sure enough, the number of NAs in each column match the numbers from the warning messages, so missing data is the culprit. How to proceed depends on your desired analysis. If you really need complete sets of date/time information, you might delete the rows or columns containing NAs.</p>
<p>As your last step, you’ll use the tidyr function unite() to combine the venue_city and venue_state columns into one column with the two values separated by a comma and a space. For example, “PORTLAND” “MAINE” should become “PORTLAND, MAINE”.</p>
<pre class="r"><code># Combine the venue_city and venue_state columns
sales6 &lt;- unite(sales5, venue_city_state, venue_city, venue_state, sep = &quot;, &quot;)


# View the head of sales6
head(sales6)</code></pre>
<pre><code>##                                                       event_name
## 1 Xfinity Center Mansfield Premier Parking: Florida Georgia Line
## 2                  Gorge Camping - dave matthews band - sept 3-7
## 3                    Dodge Theatre Adams Street Parking - benise
## 4   Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow
## 5                                  Premier Parking - motley crue
## 6                                      Fast Lane Access: Journey
##                           primary_act_name secondary_act_name major_cat_name         minor_cat_name
## 1 XFINITY Center Mansfield Premier Parking               NULL           MISC                PARKING
## 2                            Gorge Camping Dave Matthews Band           MISC                CAMPING
## 3                            Parking Event               NULL           MISC                PARKING
## 4         Gexa Energy Pavilion VIP Parking               NULL           MISC                PARKING
## 5 White River Amphitheatre Premier Parking               NULL           MISC                PARKING
## 6                         Fast Lane Access            Journey           MISC SPECIAL ENTRY (UPSELL)
##   la_event_type_cat                                                event_disp_name
## 1           PARKING Xfinity Center Mansfield Premier Parking: Florida Georgia Line
## 2           INVALID                  Gorge Camping - dave matthews band - sept 3-7
## 3           PARKING                    Dodge Theatre Adams Street Parking - benise
## 4           PARKING   Gexa Energy Pavilion Vip Parking : kid rock with sheryl crow
## 5           PARKING                                  Premier Parking - motley crue
## 6            UPSELL                                      Fast Lane Access: Journey
##                                                                                                                                                    ticket_text
## 1    THIS TICKET IS VALID        FOR PARKING ONLY         GOOD THIS DAY ONLY       PREMIER PARKING PASS    XFINITY CENTER,LOTS 4 PM  SAT SEP 12 2015 7:30 PM  
## 2                                                                %OVERNIGHT C A M P I N G%* * * * * *%GORGE CAMPGROUND%* GOOD THIS DATE ONLY *%SEP 3 - 6, 2009
## 3                               ADAMS STREET GARAGE%PARKING FOR 4/21/06 ONLY%DODGE THEATRE PARKING PASS%ENTRANCE ON ADAMS STREET%BENISE%GARAGE OPENS AT 6:00PM
## 4    THIS TICKET IS VALID        FOR PARKING ONLY      GOOD FOR THIS DATE ONLY       VIP PARKING PASS        GEXA ENERGY PAVILION    FRI SEP 02 2011 7:00 PM  
## 5                              THIS TICKET IS VALID%FOR PARKING ONLY%GOOD THIS DATE ONLY%PREMIER PARKING PASS%WHITE RIVER AMPHITHEATRE%SAT JUL 30, 2005 6:00PM
## 6         FAST LANE                  JOURNEY               FAST LANE EVENT         THIS IS NOT A TICKET    SAN MANUEL AMPHITHEATER   SAT JUL 21 2012 7:00 PM  
##   tickets_purchased_qty trans_face_val_amt delivery_type_cd   event_dt event_time presale_dt
## 1                     1                 45          eTicket 2015-09-12   23:30:00       &lt;NA&gt;
## 2                     1                 75       TicketFast 2009-09-05   01:00:00       &lt;NA&gt;
## 3                     1                  5       TicketFast 2006-04-22   01:30:00       &lt;NA&gt;
## 4                     1                 20             Mail 2011-09-03   00:00:00       &lt;NA&gt;
## 5                     1                 20             Mail 2005-07-31   01:00:00 2005-03-02
## 6                     2                 10       TicketFast 2012-07-22   02:00:00       &lt;NA&gt;
##    onsale_dt ord_create_dt ord_create_time sales_ord_tran_dt   print_dt timezn_nm
## 1 2015-05-15    2015-09-11        18:17:45        2015-09-11 2015-09-12       EST
## 2 2009-03-13    2009-07-06        00:00:00        2009-07-05 2009-09-01       PST
## 3 2006-02-25    2006-04-05        00:00:00        2006-04-05 2006-04-05       MST
## 4 2011-04-22    2011-07-01        17:38:50        2011-07-01 2011-07-06       CST
## 5 2005-03-04    2005-06-18        00:00:00        2005-06-18 2005-06-28       PST
## 6 2012-04-11    2012-07-21        17:20:18        2012-07-21 2012-07-21       PST
##             venue_city_state venue_postal_cd_sgmt_1           sales_platform_cd print_flg
## 1   MANSFIELD, MASSACHUSETTS                  02048 www.concerts.livenation.com        T 
## 2         QUINCY, WASHINGTON                  98848                        NULL        T 
## 3           PHOENIX, ARIZONA                  85003                        NULL        T 
## 4              DALLAS, TEXAS                  75210                        NULL        T 
## 5         AUBURN, WASHINGTON                  98092                        NULL        T 
## 6 SAN BERNARDINO, CALIFORNIA                  92407          www.livenation.com        T 
##   la_valid_tkt_event_flg  fin_mkt_nm
## 1                     N       Boston
## 2                     N      Seattle
## 3                     N      Arizona
## 4                     N       Dallas
## 5                     N      Seattle
## 6                     N  Los Angeles</code></pre>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
